Import('RTT_ROOT')
Import('rtconfig')
import rtconfig
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = []
# src += Glob('*.c')
# src += Glob('*.cpp')

if GetDepend('SW374_RT_THREAD_CLASS') and GetDepend('USING_SW374'):
    src += Glob(os.path.join(cwd, '*.cpp'))
    # src += Glob(os.path.join(cwd, '*.c'))




group = DefineGroup('374-rt-thread-class-cpp', src, depend = ['SW374_RT_THREAD_CLASS'], CPPPATH = CPPPATH)

Return('group')