Import('RTT_ROOT')
Import('rtconfig')
import rtconfig
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = []


if GetDepend('SW374_WIFI_CONNECT') and GetDepend('USING_SW374'):
    src = Glob(os.path.join(cwd, '*.c'))

group = DefineGroup('sw374_wifi_connect', src, depend = [''], CPPPATH = CPPPATH)

Return('group')