Import('RTT_ROOT')
Import('rtconfig')
import rtconfig
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = []


if GetDepend('SW374_DFS_FILE_CONFIG') and GetDepend('USING_SW374'):
    src = Glob(os.path.join(cwd, '*.c'))

group = DefineGroup('sw374-dfs-file-config', src, depend = ['SW374_DFS_FILE_CONFIG'], CPPPATH = CPPPATH)

Return('group')