Import('RTT_ROOT')
Import('rtconfig')
import rtconfig
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
# CPPPATH.append(cwd + '/../')
src = []


if GetDepend('SW374_TCP_SERVER') and GetDepend('USING_SW374'):
    src = Glob(os.path.join(cwd, '*.cpp'))

group = DefineGroup('sw374-tcp-server', src, depend = ['SW374_TCP_SERVER'], CPPPATH = CPPPATH)

Return('group')