from building import *
import os

cwd = GetCurrentDir()
group = []

src = []
# src += Glob('*.c')
src += Glob('./ui/*.cpp')
src += Glob('./thread/*.cpp')
# src += Glob('./thread/*.c')
src += Glob('./font/*.c')


CPPPATH = [cwd]
CPPPATH.append(cwd + './ui')
CPPPATH.append(cwd + './thread')


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

group = group + DefineGroup('LVGL-port', src, depend = ['SW374_LVGL_UI'], CPPPATH = CPPPATH)

Return('group')
