Import('RTT_ROOT')
Import('rtconfig')
import rtconfig
from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = []


if GetDepend('SW374_TELEMETRY_DATA_PROCESSOR') and GetDepend('USING_SW374'):
    src = Glob(os.path.join(cwd, '*.cpp'))

group = DefineGroup('sw374-telemetry-data-processor', src, depend = ['SW374_TELEMETRY_DATA_PROCESSOR'], CPPPATH = CPPPATH)

Return('group')