Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.cpp')

# lvgl_src_path = os.path.join(RTT_ROOT, 'packages', 'artinchip', 'lvgl-ui', 'lvgl_v9', 'lvgl', 'env_support', 'rt-thread')
# src += Glob(os.path.join(lvgl_src_path, '*.c'))

# lvgl_src_path = os.path.join(RTT_ROOT, 'packages', 'third-party', 'cherryusb', 'demo')
# src += Glob(os.path.join(lvgl_src_path, '*.c'))

CPPPATH = [cwd]
if GetDepend('SW374_DFS_FILE_CONFIG') and GetDepend('USING_SW374'):
    CPPPATH.append(cwd + '/dfs_file_config/')
if GetDepend('SW374_WIFI_CONNECT') and GetDepend('USING_SW374'):
    CPPPATH.append(cwd + '/wifi_connect/')
if GetDepend('SW374_TCP_SERVER') and GetDepend('USING_SW374'):
    CPPPATH.append(cwd + '/tcp_server/')
if GetDepend('SW374_TELEMETRY_DATA_PROCESSOR') and GetDepend('USING_SW374'):
    CPPPATH.append(cwd + '/telemetry_data_processor/')
if GetDepend('SW374_LVGL_UI') and GetDepend('USING_SW374'):
    CPPPATH.append(cwd + '/lvgl_ui/')
    

CFLAGS = ' -c -ffunction-sections'

group   = DefineGroup('Applications', src, depend = ['USING_SW374'], CPPPATH = CPPPATH, CFLAGS=CFLAGS)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
